services:
  app:
    image: "laauurraaa/scrybble-app:latest"
    restart: always
    networks:
      - app
    depends_on:
      - redis
      - remarks
      - nginx-proxy
    expose:
      - "80"
    volumes:
      - app-cache:/var/www/html/storage/framework
      - app-bootstrap-cache:/var/www/html/bootstrap/cache
      - /efs:/var/www/html/storage/efs/
      - /home/laura/.env:/var/www/html/.env
    environment:
      DB_CONNECTION: '${DB_CONNECTION}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_HOST: '${DB_HOST}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_PORT: '${DB_PORT}'
      DB_USERNAME: '${DB_USERNAME}'
      VIRTUAL_HOST: scrybble.ink
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: scrybble.ink
  on_startup:
    image: "laauurraaa/scrybble-app:latest"
    networks:
      - app
    depends_on:
      - redis
    volumes:
      - app-cache:/var/www/html/storage/framework
      - app-bootstrap-cache:/var/www/html/bootstrap/cache
      - /home/laura/.env:/var/www/html/.env
    command:
      - /bin/bash
      - -c
      - |
        php /var/www/html/artisan optimize:clear
        php /var/www/html/artisan optimize
  horizon:
    image: "laauurraaa/scrybble-app:latest"
    depends_on:
      - redis
    user: www-data
    restart:
      always
    networks:
      - app
    command: ["php", "/var/www/html/artisan", "horizon"]
    volumes:
      - app-cache:/var/www/html/storage/framework
      - app-bootstrap-cache:/var/www/html/bootstrap/cache
      - /efs:/var/www/html/storage/efs/
      - /home/laura/.env:/var/www/html/.env
    environment:
      PHP_FPM_POOL_NAME: "scrybble_horizon"
  nginx-proxy:
    restart: always
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - app
  acme-companion:
    restart: always
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=mail@scrybble.ink
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app
  redis:
    restart: always
    image: 'redis:alpine'
    volumes:
      - 'app-redis:/data'
    networks:
      - app
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
  remarks:
    restart: always
    image: "laauurraaa/remarks-server:latest"
    networks:
      - app
    volumes:
      - /efs:/efs
networks:
  app:
    driver: bridge
volumes:
  app-redis:
    driver: local
  app-cache:
    driver: local
  app-bootstrap-cache:
    driver: local
  conf:
  vhost:
  html:
  certs:
  acme:
